name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Docker image tags
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "tag_latest=latest" >> $GITHUB_OUTPUT
          echo "tag_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "tag_date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Check Secrets
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          if [ -z "$DOCKER_USER" ]; then
            echo "Error: DOCKERHUB_USERNAME secret is not set!"
            exit 1
          else
            echo "DOCKERHUB_USERNAME secret is detected (length: ${#DOCKER_USER})"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          # context: ./perception_dev_docker_origin
          # file: ./perception_dev_docker_origin/Dockerfile.txt
          context: ./perception-env
          file: ./perception-env/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            godfery110/perception-env:${{ steps.vars.outputs.tag_latest }}
            godfery110/perception-env:${{ steps.vars.outputs.tag_sha }}
            godfery110/perception-env:${{ steps.vars.outputs.tag_date }}
